spring:
  application:
    name: hello-service-invoker
  config:
    import: optional:configserver:http://config-server:${CONFIG_PORT:8888}
  profiles:
    active: default

server:
  port: ${HELLO_SERVICE_INVOKER_PORT:4568}
  address: 0.0.0.0
hello:
  service:
    url: ${HELLO_SERVICE_URL:http://localhost:4567}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
